<?php

namespace Simflex\Admin\Structure\Tables;

use Simflex\Admin\Structure\Data\FieldDefinition;
use Simflex\Admin\Structure\Data\ParamDefinition;
use Simflex\Admin\Structure\Data\TableDefinition;
use Simflex\Admin\Structure\Table;

class Content extends Table
{
    public static function name(): string
    {
        return 'content';
    }

    public static function definition(): TableDefinition
    {
        return new TableDefinition(
            name: 'content',
            orderBy: '',
            orderDesc: false,
            privAdd: null,
            privEdit: null,
            privDelete: null,
            class: \Simflex\Extensions\Content\Admin\AdminContent::class,
            fields: [
                'content_id' => new FieldDefinition(
                    name: 'content_id',
                    label: 'ID',
                    class: \Simflex\Admin\Fields\FieldInt::class,
                    npp: 1,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '1',
                            'e2n' => '1',
                            'hidden' => '1',
                            'width' => '60',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '1',
                            'onchange' => '',
                            'readonly' => '0',
                            'style_cell' => '',
                            'screen_width' => '0',
                            'width_mob' => '0',
                            'is_fk' => '0',
                            'fk_table' => '',
                            'fk_key' => '',
                            'fk_label' => '',
                            'fk_is_pid' => '0',
                        ],
                    ],
                ),
                'pid' => new FieldDefinition(
                    name: 'pid',
                    label: 'Родитель',
                    class: \Simflex\Admin\Fields\FieldInt::class,
                    npp: 3,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '1',
                            'hidden' => '0',
                            'width' => '0',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'onchange' => '',
                            'readonly' => '0',
                            'style_cell' => '',
                            'screen_width' => '0',
                            'is_fk' => '1',
                            'fk_table' => 'content',
                            'fk_key' => 'content_id',
                            'fk_label' => 'title',
                            'fk_is_pid' => '1',
                        ],
                    ],
                ),
                'active' => new FieldDefinition(
                    name: 'active',
                    label: 'Активно',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    npp: 0,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '0',
                            'width' => '104',
                            'defaultValue' => '1',
                            'required' => '0',
                            'filter' => '1',
                            'onchange' => '',
                            'readonly' => '0',
                            'style_cell' => '',
                            'screen_width' => '0',
                            'width_mob' => '0',
                        ],
                    ],
                ),
                'date' => new FieldDefinition(
                    name: 'date',
                    label: 'Дата',
                    class: \Simflex\Admin\Fields\FieldDate::class,
                    npp: 4,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '0',
                            'width' => '0',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'fk' => '',
                        ],
                    ],
                ),
                'title' => new FieldDefinition(
                    name: 'title',
                    label: 'Заголовок',
                    class: \Simflex\Admin\Fields\FieldString::class,
                    npp: 5,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '0',
                            'width' => '1',
                            'defaultValue' => '',
                            'required' => '1',
                            'filter' => '1',
                            'onchange' => '',
                            'readonly' => '0',
                            'style_cell' => '',
                            'screen_width' => '0',
                            'width_mob' => '1',
                            'pos' => '',
                            'pos_group' => '',
                        ],
                    ],
                ),
                'alias' => new FieldDefinition(
                    name: 'alias',
                    label: 'Алиас',
                    class: \Simflex\Admin\Fields\FieldAlias::class,
                    npp: 6,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '0',
                            'width' => '0',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'onchange' => '',
                            'readonly' => '0',
                            'style_cell' => '',
                            'screen_width' => '0',
                            'source' => 'title',
                        ],
                    ],
                ),
                'path' => new FieldDefinition(
                    name: 'path',
                    label: 'Путь',
                    class: \Simflex\Admin\Fields\FieldPath::class,
                    npp: 7,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '0',
                            'width' => '0',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'onchange' => '',
                            'readonly' => '1',
                            'style_cell' => '',
                        ],
                    ],
                ),
                'short' => new FieldDefinition(
                    name: 'short',
                    label: 'Коротко',
                    class: \Simflex\Admin\Fields\FieldText::class,
                    npp: 8,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '0',
                            'width' => '0',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'onchange' => '',
                            'editor_mini' => '0',
                            'editor_full' => '0',
                        ],
                    ],
                ),
                'text' => new FieldDefinition(
                    name: 'text',
                    label: 'Текст',
                    class: \Simflex\Admin\Fields\FieldText::class,
                    npp: 9,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '0',
                            'width' => '0',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'fk' => '',
                            'onchange' => '',
                            'editor_mini' => '0',
                            'editor_full' => '1',
                        ],
                    ],
                ),
                'params' => new FieldDefinition(
                    name: 'params',
                    label: 'Параметры',
                    class: \Simflex\Admin\Fields\FieldString::class,
                    npp: 10,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '1',
                            'width' => '0',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'fk' => '',
                            'onchange' => '',
                        ],
                    ],
                ),
                'photo' => new FieldDefinition(
                    name: 'photo',
                    label: 'Фото',
                    class: \Simflex\Admin\Fields\FieldImage::class,
                    npp: 11,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '1',
                            'hidden' => '0',
                            'width' => '88',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'onchange' => '',
                            'readonly' => '0',
                            'style_cell' => '',
                            'screen_width' => '0',
                            'width_mob' => '50',
                            'pos' => '',
                            'pos_group' => '',
                            'path' => 'content',
                            'small' => '200x150',
                            'medium' => '',
                            'large' => '800x600',
                        ],
                    ],
                ),
                'template_id' => new FieldDefinition(
                    name: 'template_id',
                    label: 'Шаблон',
                    class: \Simflex\Admin\Fields\FieldInt::class,
                    npp: 2,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '1',
                            'hidden' => '0',
                            'width' => '176',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '1',
                            'onchange' => '',
                            'readonly' => '0',
                            'style_cell' => '',
                            'screen_width' => '0',
                            'width_mob' => '0',
                            'is_fk' => '1',
                            'fk_table' => 'content_template',
                            'fk_key' => 'template_id',
                            'fk_label' => 'template_name',
                            'fk_is_pid' => '0',
                        ],
                    ],
                ),
                'npp' => new FieldDefinition(
                    name: 'npp',
                    label: '№ п/п',
                    class: \Simflex\Admin\Fields\FieldNPP::class,
                    npp: 3,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => [
                            'pk' => '0',
                            'e2n' => '0',
                            'hidden' => '0',
                            'width' => '107',
                            'defaultValue' => '',
                            'required' => '0',
                            'filter' => '0',
                            'onchange' => '',
                            'readonly' => '0',
                            'style_cell' => '',
                            'screen_width' => '0',
                            'width_mob' => '0',
                        ],
                    ],
                ),
            ],
            params: [
                'content_main' => new ParamDefinition(
                    name: 'content_main',
                    label: 'Вывод данных',
                    class: null,
                    paramId: 18,
                    paramPid: '',
                    pos: 'right',
                    defaultValue: '',
                    params: [],
                ),
                'tpl' => new ParamDefinition(
                    name: 'tpl',
                    label: 'Шаблон вывода',
                    class: \Simflex\Admin\Fields\FieldString::class,
                    paramId: 19,
                    paramPid: 18,
                    pos: '',
                    defaultValue: 'mod_list.tpl',
                    params: [],
                ),
                'cnt_limit' => new ParamDefinition(
                    name: 'cnt_limit',
                    label: 'Количество',
                    class: \Simflex\Admin\Fields\FieldInt::class,
                    paramId: 20,
                    paramPid: 18,
                    pos: '',
                    defaultValue: '3',
                    params: [],
                ),
                'content_view' => new ParamDefinition(
                    name: 'content_view',
                    label: 'Внешний вид',
                    class: null,
                    paramId: 21,
                    paramPid: '',
                    pos: 'right',
                    defaultValue: '',
                    params: [],
                ),
                'date' => new ParamDefinition(
                    name: 'date',
                    label: 'Дата',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    paramId: 22,
                    paramPid: 21,
                    pos: '',
                    defaultValue: '',
                    params: [],
                ),
                'short' => new ParamDefinition(
                    name: 'short',
                    label: 'Анонс',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    paramId: 23,
                    paramPid: 21,
                    pos: '',
                    defaultValue: '0',
                    params: [],
                ),
                'more' => new ParamDefinition(
                    name: 'more',
                    label: 'Кнопка далее',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    paramId: 24,
                    paramPid: 21,
                    pos: '',
                    defaultValue: '0',
                    params: [],
                ),
                'more_text' => new ParamDefinition(
                    name: 'more_text',
                    label: 'Текст на кнопке далее',
                    class: \Simflex\Admin\Fields\FieldString::class,
                    paramId: 25,
                    paramPid: 21,
                    pos: '',
                    defaultValue: 'Читать далее',
                    params: [],
                ),
                'hide_title' => new ParamDefinition(
                    name: 'hide_title',
                    label: 'Не показывать заголовок',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    paramId: 26,
                    paramPid: 21,
                    pos: '',
                    defaultValue: '0',
                    params: [
                        'main' => [
                            'defaultValue' => '0',
                        ],
                    ],
                ),
            ],
        );
    }
}
