<?php

namespace Simflex\Admin\Structure\Tables;

use Simflex\Admin\Structure\Data\FieldDefinition;
use Simflex\Admin\Structure\Data\FieldParams;
use Simflex\Admin\Structure\Data\ParamDefinition;
use Simflex\Admin\Structure\Data\TableDefinition;
use Simflex\Admin\Structure\Table;

class Content extends Table
{
    public static function name(): string
    {
        return 'content';
    }

    public static function definition(): TableDefinition
    {
        return new TableDefinition(
            name: 'content',
            orderBy: '',
            orderDesc: false,
            privAdd: null,
            privEdit: null,
            privDelete: null,
            class: \Simflex\Extensions\Content\Admin\AdminContent::class,
            fields: [
                'content_id' => new FieldDefinition(
                    name: 'content_id',
                    label: 'ID',
                    class: \Simflex\Admin\Fields\FieldInt::class,
                    npp: 1,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: true,
                            e2n: true,
                            hidden: true,
                            width: '60',
                            defaultValue: '',
                            required: false,
                            filter: true,
                            onchange: '',
                            readonly: false,
                            styleCell: '',
                            screenWidth: '0',
                            widthMob: '0',
                            isFk: false,
                            fkTable: '',
                            fkKey: '',
                            fkLabel: '',
                            fkIsPid: false,
                        ),
                    ],
                ),
                'pid' => new FieldDefinition(
                    name: 'pid',
                    label: 'Родитель',
                    class: \Simflex\Admin\Fields\FieldInt::class,
                    npp: 3,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: true,
                            hidden: false,
                            width: '0',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            onchange: '',
                            readonly: false,
                            styleCell: '',
                            screenWidth: '0',
                            isFk: true,
                            fkTable: 'content',
                            fkKey: 'content_id',
                            fkLabel: 'title',
                            fkIsPid: true,
                        ),
                    ],
                ),
                'active' => new FieldDefinition(
                    name: 'active',
                    label: 'Активно',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    npp: 0,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: false,
                            width: '104',
                            defaultValue: '1',
                            required: false,
                            filter: true,
                            onchange: '',
                            readonly: false,
                            styleCell: '',
                            screenWidth: '0',
                            widthMob: '0',
                        ),
                    ],
                ),
                'date' => new FieldDefinition(
                    name: 'date',
                    label: 'Дата',
                    class: \Simflex\Admin\Fields\FieldDate::class,
                    npp: 4,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: false,
                            width: '0',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            fk: '',
                        ),
                    ],
                ),
                'title' => new FieldDefinition(
                    name: 'title',
                    label: 'Заголовок',
                    class: \Simflex\Admin\Fields\FieldString::class,
                    npp: 5,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: false,
                            width: '1',
                            defaultValue: '',
                            required: true,
                            filter: true,
                            onchange: '',
                            readonly: false,
                            styleCell: '',
                            screenWidth: '0',
                            widthMob: '1',
                            pos: '',
                            posGroup: '',
                        ),
                    ],
                ),
                'alias' => new FieldDefinition(
                    name: 'alias',
                    label: 'Алиас',
                    class: \Simflex\Admin\Fields\FieldAlias::class,
                    npp: 6,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: false,
                            width: '0',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            onchange: '',
                            readonly: false,
                            styleCell: '',
                            screenWidth: '0',
                            source: 'title',
                        ),
                    ],
                ),
                'path' => new FieldDefinition(
                    name: 'path',
                    label: 'Путь',
                    class: \Simflex\Admin\Fields\FieldPath::class,
                    npp: 7,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: false,
                            width: '0',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            onchange: '',
                            readonly: true,
                            styleCell: '',
                        ),
                    ],
                ),
                'short' => new FieldDefinition(
                    name: 'short',
                    label: 'Коротко',
                    class: \Simflex\Admin\Fields\FieldText::class,
                    npp: 8,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: false,
                            width: '0',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            onchange: '',
                            editorMini: false,
                            editorFull: false,
                        ),
                    ],
                ),
                'text' => new FieldDefinition(
                    name: 'text',
                    label: 'Текст',
                    class: \Simflex\Admin\Fields\FieldText::class,
                    npp: 9,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: false,
                            width: '0',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            fk: '',
                            onchange: '',
                            editorMini: false,
                            editorFull: true,
                        ),
                    ],
                ),
                'params' => new FieldDefinition(
                    name: 'params',
                    label: 'Параметры',
                    class: \Simflex\Admin\Fields\FieldString::class,
                    npp: 10,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: true,
                            width: '0',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            fk: '',
                            onchange: '',
                        ),
                    ],
                ),
                'photo' => new FieldDefinition(
                    name: 'photo',
                    label: 'Фото',
                    class: \Simflex\Admin\Fields\FieldImage::class,
                    npp: 11,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: true,
                            hidden: false,
                            width: '88',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            onchange: '',
                            readonly: false,
                            styleCell: '',
                            screenWidth: '0',
                            widthMob: '50',
                            pos: '',
                            posGroup: '',
                            path: 'content',
                            small: '200x150',
                            medium: '',
                            large: '800x600',
                        ),
                    ],
                ),
                'template_id' => new FieldDefinition(
                    name: 'template_id',
                    label: 'Шаблон',
                    class: \Simflex\Admin\Fields\FieldInt::class,
                    npp: 2,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: true,
                            hidden: false,
                            width: '176',
                            defaultValue: '',
                            required: false,
                            filter: true,
                            onchange: '',
                            readonly: false,
                            styleCell: '',
                            screenWidth: '0',
                            widthMob: '0',
                            isFk: true,
                            fkTable: 'content_template',
                            fkKey: 'template_id',
                            fkLabel: 'template_name',
                            fkIsPid: false,
                        ),
                    ],
                ),
                'npp' => new FieldDefinition(
                    name: 'npp',
                    label: '№ п/п',
                    class: \Simflex\Admin\Fields\FieldNPP::class,
                    npp: 3,
                    help: '',
                    placeholder: '',
                    params: [
                        'main' => new FieldParams(
                            pk: false,
                            e2n: false,
                            hidden: false,
                            width: '107',
                            defaultValue: '',
                            required: false,
                            filter: false,
                            onchange: '',
                            readonly: false,
                            styleCell: '',
                            screenWidth: '0',
                            widthMob: '0',
                        ),
                    ],
                ),
            ],
            params: [
                'content_main' => new ParamDefinition(
                    name: 'content_main',
                    label: 'Вывод данных',
                    class: null,
                    paramId: 18,
                    paramPid: '',
                    pos: 'right',
                    defaultValue: '',
                    params: [],
                ),
                'tpl' => new ParamDefinition(
                    name: 'tpl',
                    label: 'Шаблон вывода',
                    class: \Simflex\Admin\Fields\FieldString::class,
                    paramId: 19,
                    paramPid: 18,
                    pos: '',
                    defaultValue: 'mod_list.tpl',
                    params: [],
                ),
                'cnt_limit' => new ParamDefinition(
                    name: 'cnt_limit',
                    label: 'Количество',
                    class: \Simflex\Admin\Fields\FieldInt::class,
                    paramId: 20,
                    paramPid: 18,
                    pos: '',
                    defaultValue: '3',
                    params: [],
                ),
                'content_view' => new ParamDefinition(
                    name: 'content_view',
                    label: 'Внешний вид',
                    class: null,
                    paramId: 21,
                    paramPid: '',
                    pos: 'right',
                    defaultValue: '',
                    params: [],
                ),
                'date' => new ParamDefinition(
                    name: 'date',
                    label: 'Дата',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    paramId: 22,
                    paramPid: 21,
                    pos: '',
                    defaultValue: '',
                    params: [],
                ),
                'short' => new ParamDefinition(
                    name: 'short',
                    label: 'Анонс',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    paramId: 23,
                    paramPid: 21,
                    pos: '',
                    defaultValue: '0',
                    params: [],
                ),
                'more' => new ParamDefinition(
                    name: 'more',
                    label: 'Кнопка далее',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    paramId: 24,
                    paramPid: 21,
                    pos: '',
                    defaultValue: '0',
                    params: [],
                ),
                'more_text' => new ParamDefinition(
                    name: 'more_text',
                    label: 'Текст на кнопке далее',
                    class: \Simflex\Admin\Fields\FieldString::class,
                    paramId: 25,
                    paramPid: 21,
                    pos: '',
                    defaultValue: 'Читать далее',
                    params: [],
                ),
                'hide_title' => new ParamDefinition(
                    name: 'hide_title',
                    label: 'Не показывать заголовок',
                    class: \Simflex\Admin\Fields\FieldBool::class,
                    paramId: 26,
                    paramPid: 21,
                    pos: '',
                    defaultValue: '0',
                    params: [
                        'main' => new FieldParams(
                            defaultValue: '0',
                        ),
                    ],
                ),
            ],
        );
    }
}
